### DISCUSSION TITLE
Does Mike work with GitLab Pages?

### DISCUSSION THREAD

**Discussion by marcela-fernanda** [jimporter/mike#186] [Q&A]

**Comment by jimporter** [comment]
I'm not actually sure. It probably does? (I've never used Gitlab, so I don't know much about how its pages work.)

At worst, you could manually generate the docs and put them somewhere, and hopefully Gitlab would be happy with that. You might also be able to do it as part of Gitlab's CI to auto-generate docs whenever you push some commits.

**Comment by marcela-fernanda** [comment]
> You might also be able to do it as part of Gitlab's CI to auto-generate docs whenever you push some commits.

I try to do that but it didn't work 👎 

I currently have gh-pages branch and CI has mike installation instruction (`pip install mike`), but now i'm having problems with CORS

![error-blue](https://user-images.githubusercontent.com/42184254/99301818-44551c80-282d-11eb-97ae-4634bd76b959.jpg)

**Comment by jimporter** [comment]
Hmm. Unfortunately, Gitlab isn't my area of expertise, so I'm not sure I can be much help. If anyone else out there knows how to get this working on Gitlab though, I'd be happy to add some documentation explaining the details.

**Comment by hpsems** [comment]
Im having the same issue trying to deploy my versioned docs with mkdocs-material and mike via Gitlab Pages. mike creates a gh-pages branch wich contains all my deployed versions and aliases and also the versions.json but im unable to get Pages to deploy the versioned docs. If someone solves this please let me know! A documentation on this would be great!

**Comment by snim2** [comment]
I'm also trying to use `mike` with GitLab pages. If I do get it figured out I'd be happy to contribute some docs.

**Comment by hpsems** [comment]
We found a solution that works well for us:
When using `mike deploy` the generated version of the site will be pushed to the `gh-pages` branch by default. Gitlab expects a folder 'public' for its [pages function](https://docs.gitlab.com/ee/user/project/pages/). To your docs with GitLab-Pages you simply have to move the contents of the `gh-pages` branch into the public folder. Add a pipeline via a **.gitlab-ci.yml** file to the gh-pages branch, that looks like this:

```
image: alpine:3.13
pages:
  stage: deploy
  only:
    - gh-pages
  script:
    - mkdir .public
    - cp -r * .public
    - mv .public public
    - ls
  artifacts:
    paths:
      - public
```

**Edit:** We now use alpine, since there is no need for python to move the files.

The gh-pages branch looks like this, where the folders contain a version of the docs each:

![image](https://user-images.githubusercontent.com/78910056/120300087-e5885980-c2cb-11eb-9544-dab94e83d70c.png)

Hope this helps.

**Comment by rogedelgado** [comment]
Hello @hpsem 

I'm struggling with adding the .gitlab-ci.yml file in the branch gh-pages. I added that file directly from the web IDE that gitlab.com provides, but I'm getting a error when  I try to deploy some changes in the docs from another branch (say **some_docs** for instance). 

The ci/cd pipeline that runs with the mike deploy step raise an error that said:

```
error: failed to push branch gh-pages to http://cissf:[MASKED]@gitlab.com/group/repo.git: "warning: redirecting to https://gitlab.com/group/repo.git/
To http://gitlab.com/group/repo.git
 ! [rejected]            gh-pages -> gh-pages (non-fast-forward)
error: failed to push some refs to 'http://cissf:[MASKED]@gitlab.com/group/repo.git'
hint: Updates were rejected because a pushed branch tip is behind its remote
hint: counterpart. Check out this branch and integrate the remote changes
hint: (e.g. 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details."
```

The deploy command that is executed is this:

```
mike deploy -r http://cissf:$GITLAB_TOKEN@gitlab.com/group/repo.git -b gh-pages --rebase -p 1.23
```
I use the `--rebase` option in an attempt to rebase any changes that the remote branch may have but didn't work, I get the same result.

So, after all this, what's the best way to add the .gitlab-ci.yml file to the gh-pages branch? Do I need to add it from the WebIDE that gitlab.com provides or is there another way to do it?

Thanks for any advice, cheers!

**Comment by hpsems** [comment]
To add the .gitlab-ci.yml you can treat the gh-pages branch like any other branch. Use `git checkout gh-pages`, add the file, commit and push. Then switch back to the branch where you keep your docs folder and deploy via mike. Now the pipeline should be triggered by the commit that mike creates when deploying.
Keep in mind that when you use the webIDE to add a file, you need to pull the changes to your local repo before deploying.

**Edit:** I updated my previous post to be more clear how this works, hope this helps.

**Comment by rogedelgado** [comment]
Thanks for the reply, I manage to get it to work. The mistake I was making is that I do not checkout and pull the changes to the gh-pages branch in my pipeline before the `mike deploy` command.

**Comment by zhilyaev** [comment]
My solution with **semver**.
I create branch for each minor version. Like that 0.12.x.

```yaml
name: Publish docs via GitHub Pages
on:
  push:
    branches:
    - '*.*.x'


jobs:
  upload:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - uses: actions/setup-python@v2
      with:
        python-version: "3.9"

    - name: Cache pip
      uses: actions/cache@v2
      with:
        # This path is specific to Ubuntu
        path: ~/.cache/pip
        # Look to see if there is a cache hit for the corresponding requirements file
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          ${{ runner.os }}-
    - name: Install dependencies
      run: pip install -r requirements.txt


    - name: Set user
      run: |
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch

    - name: Mike
      run: |
        mike deploy --push ${{ steps.extract_branch.outputs.branch }}
```

[src](https://github.com/helmwave/docs/blob/d72cf7403d8b8b812c064b5c1579b21940a52369/.github/workflows/publish-b.yml)

And manually bump minor version to latest :) 

```yaml
extra:
  version:
    provider: mike
    default: latest
```

**Comment by nejch** [comment]
I wanted to get close to a native GitLab Pages experience out of the box - CI only/without local deploys, no manual steps for initially creating a pages branch and no custom `.gitlab-ci.yml` in a separate branch, so that normal git workflows can be used by developers.

This example is deploying on tags only and sets each tag as latest. The pages branch is only used by CI as storage for persisting `public/` artifacts, which are then checked out in the job itself so they can be consumed by `artifacts:`.

Prerequisites:
- the image used for the `pages` job should have git & mike etc installed, so it can push automatically (you could also add this to `before_script`)
- create a project access token (or use another PAT), with e.g. CI variables `PROJECT_BOT_USER` (its username) and `PROJECT_BOT_TOKEN` (the token)

```yaml
pages:
  stage: deploy
  variables:
    PAGES_BRANCH: pages
    HTTPS_REMOTE: https://${PROJECT_BOT_USER}:${PROJECT_BOT_TOKEN}@${CI_SERVER_HOST}/${CI_PROJECT_PATH}.git
  before_script:
    - git config user.name $PROJECT_BOT_USER
    - git config user.email $PROJECT_BOT_USER@gitlab.example.com
    - git fetch origin $PAGES_BRANCH && git checkout -b $PAGES_BRANCH origin/$PAGES_BRANCH || echo "Pages branch not deployed yet."
    - git checkout $CI_COMMIT_SHA
  script:
    - mike deploy --rebase --prefix public -r $HTTPS_REMOTE -p -b $PAGES_BRANCH $CI_COMMIT_TAG
    - mike set-default --rebase --prefix public -r $HTTPS_REMOTE -p -b $PAGES_BRANCH $CI_COMMIT_TAG
    - git checkout $PAGES_BRANCH -- public/
  artifacts:
    paths:
      - public/
  only:
    - tags
```

Room for improvement:
- I'm sure some of the script step could be cleaned up a bit, let me know
- squashing to always only have a single commit would make the gitlab graph look much nicer, this will always show an orphaned pages branch with its own history otherwise.
- if gitlab implements pushing via `CI_JOB_TOKEN`, no token setup would be required (upstream: https://gitlab.com/gitlab-org/gitlab/-/issues/223679)
- alternatively if `CI_JOB_TOKEN` could fetch previous job artifacts, pushing to branches could be eliminated entirely (and just always take what's already deployed to Pages in `public/` perhaps.

If anyone tries this I'd be interested if it works out for you, but the snippet above should _just work_ if you add git, mike and your mkdocs dependencies as well, and then start tagging your docs (I'm sure it can be extended so you can use both tags and master deployments though, just haven't tried).

**Comment by ExplGamma** [comment]
For anyone still looking into this, can I also propose an alternative solution to nejch's, mostly similar however:

```yaml
pages:
  stage: deploy
  image: python:latest
  variables:
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
    PAGES_BRANCH: gl-pages
    HTTPS_REMOTE: https://gitlab-ci-token:${ACCESS_TOKEN}@${CI_SERVER_HOST}/${CI_PROJECT_PATH}.git
  before_script:
    - pip install mkdocs-material mike
    - git config user.name $GITLAB_USER_NAME
    - git config user.email $GITLAB_USER_EMAIL
    - git fetch origin $PAGES_BRANCH && git -b checkout $PAGES_BRANCH origin/$PAGES_BRANCH || git checkout $PAGES_BRANCH || echo "Pages branch not deployed yet."
    - git checkout $CI_COMMIT_SHA
  script:
   - mike deploy --rebase --prefix public -r $HTTPS_REMOTE -p -b $PAGES_BRANCH -u $CI_COMMIT_TAG latest
   - mike set-default --rebase --prefix public -r $HTTPS_REMOTE -p -b $PAGES_BRANCH latest
   - git checkout $PAGES_BRANCH -- public/
  artifacts:
    paths:
     - public/
  only:
    - tags
```

Don't forget to create an access token and save it as a CI/CD variable in settings.

Solution mostly found [here](https://stackoverflow.com/questions/72467521/auto-deploy-mkdocs-with-versionning-using-mike-on-gitlab-pages) - needed some minor changes to make it work however

**Comment by nejch** [comment]
I guess that just basically adds the dependencies which as described above will really depend on your pip/docker image/poetry setup etc :) `gitlab-ci-token` usually implies CI job token so not sure that's a safe assumption for the username going forward but might be cleaner for now.

**Comment by igloo15** [comment]
This solution no longer works seems like mike cli has changed and there are invalid arguments

**Reply by leodevian** [reply]
You can remove the `--rebase` and replace `--prefix` with `--deploy-prefix`.

**Comment by danibcorr** [comment]
Hi, if someone want to use GitLab Pages for documentation, **but your project requires GPG‑signed commits**, the following setup worked for [us](https://ericsson.github.io/cognitive-labs/). The example assume:

- You have a docs branch variable `$GIT_PAGES_BRANCH_NAME` defined in your .gitlab-ci.yml (e.g. GIT_PAGES_BRANCH_NAME: gl-pages).
- You store your GPG private key and email as CI/CD variables:
  - `GITLAB_GPG_PRIVATE_KEY_BASE64` (base64‑encoded private key)
  - `GITLAB_GPG_EMAIL` (email that matches the GPG key)

First, this template installs Git and GPG, imports a base64‑encoded private key, configures Git user info, and enforces GPG‑signed commits:

```yaml
.setup_git_gpg: &setup_git_gpg
  # Update packages and install git and gnupg for gpg signing
  - apt-get update && apt-get install -y git gnupg

  # Import GPG private key from CI variable
  - echo "$GITLAB_GPG_PRIVATE_KEY_BASE64" | base64 -d | gpg --batch --import
  
  # Extract GPG key ID
  - export GPG_KEY_ID=$(gpg --list-secret-keys --keyid-format LONG | grep sec | awk
    '{print $2}' | cut -d'/' -f2)
  
  # Configure Git user and signing key
  - git config --global user.name "${GITLAB_USER_NAME:-GitLab CI}"
  - git config --global user.email "$GITLAB_GPG_EMAIL"
  - git config --global user.signingkey "$GPG_KEY_ID"
  - git config --global commit.gpgsign true
  
  # Make sure the origin URL uses the CI job token
  - git config --global
    url."https://gitlab-ci-token:${CI_JOB_TOKEN}@${CI_SERVER_HOST}/".insteadOf
    "https://${CI_SERVER_HOST}/"
```

Then, this job creates the documentation branch:

```yaml
setup_docs_branch:
  stage: docs
  needs:
    - test
  rules:
    - if: $CI_COMMIT_BRANCH =~ /^(main|dev)$/
  before_script:
    - *setup_git_gpg
  script: |
    if ! git ls-remote --heads origin ${GIT_PAGES_BRANCH_NAME} | grep -q ${GIT_PAGES_BRANCH_NAME}; then
      git branch -D ${GIT_PAGES_BRANCH_NAME} 2>/dev/null || true
      git checkout --orphan ${GIT_PAGES_BRANCH_NAME}
      git reset --hard
      git commit --allow-empty -m "Initial ${GIT_PAGES_BRANCH_NAME} commit"
      git push origin ${GIT_PAGES_BRANCH_NAME}
    fi
```

Now we can run `mike`, update the docs branch, and keep all commits GPG‑signed:

```yaml
build_docs:
  stage: docs
  needs:
    - setup_docs_branch
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
  variables:
    <<: *submodules
    GIT_DEPTH: 0
  before_script:
    - *setup_git_gpg
  script:
    # Get project version
    - VERSION=$(uv version --short)
    # Fetch and checkout docs branch to get last commit reference
    - git fetch origin ${GIT_PAGES_BRANCH_NAME}
    - git checkout -B ${GIT_PAGES_BRANCH_NAME} origin/${GIT_PAGES_BRANCH_NAME}
    - LAST_COMMIT=$(git rev-parse ${GIT_PAGES_BRANCH_NAME})
    # Return to main branch and update submodules
    - git checkout ${CI_COMMIT_REF_NAME}
    - git submodule sync --recursive
    - git submodule update --init --recursive --force
    # Build documentation
    - uv run mike delete "v${VERSION}" --branch ${GIT_PAGES_BRANCH_NAME} || true
    - uv run mike deploy --branch ${GIT_PAGES_BRANCH_NAME} --update-aliases
      "v${VERSION}" latest
    - uv run mike set-default --branch ${GIT_PAGES_BRANCH_NAME} latest
    # Sign all commits created
    - git checkout ${GIT_PAGES_BRANCH_NAME}
    - git rebase --exec 'git commit --amend --no-edit -n -S' $LAST_COMMIT
    - git push origin ${GIT_PAGES_BRANCH_NAME}
```

> Note: `uv` is just our tool to manage Python environments and dependencies; you can replace it with your own tooling. This is not relevant.

Finally, this job copies the docs from the docs branch into a `public/` directory so GitLab Pages can publish them:

```yaml
deploy_docs:
  image: alpine:latest
  stage: docs
  pages: true
  cache: []
  needs:
    - build_docs
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
  variables:
    GIT_DEPTH: 0
  before_script:
    - apk add --no-cache git
    - git fetch origin ${GIT_PAGES_BRANCH_NAME}
    - git checkout -B ${GIT_PAGES_BRANCH_NAME} origin/${GIT_PAGES_BRANCH_NAME}
  script:
    - rm -rf public
    - mkdir .public
    - cp -r * .public
    - mv .public public
  artifacts:
    paths:
      - public
```

Also, make sure this option is enabled in your GitLab project under: Settings → CI/CD → Job token permissions

<img width="970" height="163" alt="image" src="https://github.com/user-attachments/assets/0a5c7126-7fdb-4862-a9f9-65d41e5ac15d" />

Hope this helps :).
