### DISCUSSION TITLE
Unexpected behavior while deploying to custom branch

### DISCUSSION THREAD

**Discussion by sceptic30** [jimporter/mike#200] [Q&A]
Im facing an unexpected behavior while deploying with the command:
`mike deploy -b v4.0 -m v4.0_MikeDeployment v4.0`

I see that the site directory is populated with hmtl files and folders, but there is no versioned folder, no version.json, no index.html.
When I execute `git status` I see that the said wanted folder (v4.0) has been deleted along with all the other related files that Mike normally produces.

Is there any workaround for this problem? is this the expected behavior?
If I remove the branch switch `-b`, then Mike automatically creates a gh-pages branch, where I can see the v4.0 folder along with all the Mike related files.
Why is this happening?

My mkdocs (Mike) config is:
```
plugins:
  - search
  - mike:
      alias_type: copy
      redirect_template: null
      deploy_prefix: ''
      canonical_version: latest
      version_selector: true
      css_dir: stylesheets
      javascript_dir: javascripts
```
