### DISCUSSION TITLE
How to add label in front of version dropdown

### DISCUSSION THREAD

**Discussion by MartinHugh** [jimporter/mike#211] [General]
I have used mike to add versioning to some documentation, and have the dropdown available in a top left hand panel. We are using the following mkdocs.yml

```
site_name: This Site Name

theme:
  name: readthedocs
  locale: en
  navigation_depth: 3
  include_sidebar: false
  icon:
    repo: fontawesome/brands/git

```
We would like to display the word "version" to the left of the dropdown.  Is this possible?

Thanks
