### DISCUSSION TITLE
How to use nginx to publish multi-version documents?

### DISCUSSION THREAD

**Discussion by Sheldon-Hsu** [jimporter/mike#232] [Q&A]
Hi guys, I have a question about using nginx to publish multiple versions. When I used ```mike serve``` to test multiple versions, I had normal access to multiple versions of the document (eg:127.0.0.1/1.0.0/index), but when I published the document using nginx, there was no version information in the URL (eg:127.0.0.1/index). my mkdocs.yml likes:

```
extra:
  version:
    provider: mike
plugins:
  - mike:
      alias_type: symlink
      redirect_template: null
      deploy_prefix: ''
      canonical_version: null
      version_selector: true
      css_dir: css
      javascript_dir: js
```
