### DISCUSSION TITLE
full working example with readthedocs theme

### DISCUSSION THREAD

**Discussion by kelly-sovacool** [jimporter/mike#237] [Q&A] [answered]
Does anyone have a full working example of using mike with the readthedocs theme? I had it working with the material theme, but now struggling to make it work with readthedocs. 

```yaml
theme:
  name: readthedocs
  locale: en

plugins:
  - mike:
      alias_type: symlink
      canonical_version: latest
      version_selector: true
      css_dir: css
      javascript_dir: js
```

The `css` and `js` directories contain the code from https://github.com/jimporter/mike/tree/master/mike/themes/mkdocs
