### ISSUE TITLE
How to deploy to other code repository

### ISSUE THREAD

**Issue by mcxinyu** [jimporter/mike#129]
How to deploy to other code repository

My document repository and deployment repository are not the same repository.
Can I deploy documents to different repository?

**Comment by jimporter** [comment]
I think this would work:
```
cd /path/to/your/deployment/repo
mike deploy --config-file path/to/your/document/repo/mkdocs.yml
```

**Comment by mcxinyu** [comment]
Oh, I deployed by GitHub action CI, which is not operated locally.

I'm not sure if I can clone external projects in CI.

**Comment by jimporter** [comment]
You can:

```yaml
      # Clone the current repo
      - uses: actions/checkout@v3
      # Clone some other repo
      - uses: actions/checkout@v3
        with:
          repository: user/repository
          path: somewhere
```
