### ISSUE TITLE
Does mike work with mkdocs-material

### ISSUE THREAD

**Issue by snim2** [jimporter/mike#13]
On Python 3.7.5 with these packages:

```
Click==7.0
htmlmin==0.1.12
Jinja2==2.10.1
jsmin==2.2.2
livereload==2.6.1
Markdown==3.1.1
MarkupSafe==1.1.1
mike==0.5.0
mkdocs==1.0.4
mkdocs-material==4.4.2
mkdocs-minify-plugin==0.2.1
mkdocs-versioning==0.1.0
packaging==20.3
pep562==1.0
pkg-resources==0.0.0
Pygments==2.4.2
pymdown-extensions==6.1
pyparsing==2.4.6
PyYAML==5.1.2
ruamel.yaml==0.16.10
ruamel.yaml.clib==0.2.0
six==1.12.0
tornado==6.0.3
```

`mike`'s output looks like this for me:

![mike-version-screeni](https://user-images.githubusercontent.com/97674/76075543-1d9fd000-5f95-11ea-89b8-c7b00fe00c9f.png)

Is this the expected styling?

This is from `mkdocs.yml`:

```yaml
extra_css:
    - assets/css/extra.css
    - assets/css/version-select.css
extra_javascript:
    - assets/js/version-select.js
```

I've moved the files around, but not changed them. My `.gitconfig` is set up with user info.

`mike list` says:

```
$ mike list
0.0.2 [latest]
0.0.1
```

and the default docs are 0.0.2.
