### ISSUE TITLE
Keep mkdocs.yml formatting

### ISSUE THREAD

**Issue by pawamoy** [jimporter/mike#16]
A simple cosmetic issue, not important :slightly_smiling_face: 

I've ran `mike install-extras` in one of my repositories, and it reformatted my `mkdocs.yml` file.

- it removed double-quotes around strings. I guess this is just how YAML dumps works. If the string starts with a special character, it is enclosed in single-quotes, so this is safe.
- it indented items in arrays by 2 spaces (both are supported, but maybe this is recommended by YAML?)
- it added a css file and a js one, but the blank lines are wrong:

Before:

```yaml
extra_css:
  - css/mkdocstrings.css

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - pymdownx.superfences
  - pymdownx.emoji
  - toc:
      permalink: "¤"

plugins:
  - search
  - mkdocstrings:
      watch:
        - src/mkdocstrings
```

After:

```yaml
extra_css:
  - css/mkdocstrings.css

  - css/version-select.css
markdown_extensions:
  - admonition
  - codehilite:
        guess_lang: false
  - pymdownx.superfences
  - pymdownx.emoji
  - toc:
        permalink: ¤

plugins:
  - search
  - mkdocstrings:
        watch:
          - src/mkdocstrings
extra_javascript:
  - js/version-select.js
```

Note the extra blank line between the two css files, and the missing blank lines before `markdown_extensions` and `extra_javascript`.

Would it possible to keep the formatting intact, and to fix these blank lines?
