### ISSUE TITLE
Some config values are not supported despite that they are mentioned in Configuration description.

### ISSUE THREAD

**Issue by MRosiek** [jimporter/mike#178]
# Summary
When configuring **deploy_prefix** in **mkdocs.yml** file, `mike` is throwing following info:
**Config value 'plugins': Plugin 'mike' option 'deploy_prefix': Unrecognised configuration name: deploy_prefix**

# Configuration and Logs
My `mkdocs.yml` file:
```
plugins:
  - search
  - include_dir_to_nav:
  - autorefs
  - mike:
      deploy_prefix: 'documentation/site/mike_docs'
      canonical_version: null
      version_selector: true
      css_dir: css
      javascript_dir: js
```

* Repository: 
* Platform: Windows 10
* `mike` version: **1.1.2**

# Steps to Reproduce
1. configure deploy_prefix in mkdocs.yml file
2. call `mike list` or any other command like `mike delete --all`

# Expected Behavior
Config should be set as mentioned in description.
