### ISSUE TITLE
Error while deploying with emoji.twemoji

### ISSUE THREAD

**Issue by JulioV** [jimporter/mike#24]
I found the following error while trying to deploy a site with `pymdownx.emoji` extension enabled, python 3.7.3 and mike 0.5.3 on MacOS 10.15.7:

```bash
mike: could not determine a constructor for the tag 'tag:yaml.org,2002:python/name:materialx.emoji.twemoji'
```

The minimal reproducible example is a site with the following `mkdocs.yaml`

```yaml
site_name: Test
markdown_extensions:
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg
nav:
  - Home: 'index.md'
```
