### ISSUE TITLE
Could we add a configuration item for the default branch name

### ISSUE THREAD

**Issue by nkmcalli** [jimporter/mike#245]
Assumptions:

- Mike uses a local branch to store it's work, even if you don't push the branch to your remote (immediately with --push, or ever).
- Not every GitHub project hosts the docs on GitHub pages, some projects create the docs on GitHub but then host them elsewhere.

Request for enhancement:

Could we add a configuration item for the default branch name like this:

```
plugins:
  - mike:
      # These fields are all optional; the defaults are as below...
      default_branch: gh-pages
      ...
```
