### ISSUE TITLE
Can mike add a banner for old doc versions?

### ISSUE THREAD

**Issue by JulioV** [jimporter/mike#26]
Can mike add a banner to let users know that they are looking at an old version of the docs (similar to readthedocs)? If not, what would be a good way to implement this functionality?

EDIT: Maybe by outputting the banner as a markdown file which can be injected on a template block depending on the theme (e.g. [mkdocs-material announcement bar](https://squidfunk.github.io/mkdocs-material/setup/setting-up-the-header/))?

**Comment by jimporter** [comment]
It should be pretty straightforward to customize the extra CSS/JS to do this. For the `mkdocs` theme, you'd just need to check if the current version is the most recent somewhere in here, and then maybe set an attribute on the `<body>` tag that your CSS does something with:

https://github.com/jimporter/mike/blob/fbb05bbd9f11c1fea2bec1621dce23640203aece/mike/themes/mkdocs/js/version-select.js#L45-L73

Of course, themes that have built-in support for mike could do something similar internally.

Broadly speaking, I consider mike to be feature complete (at least for the time being), so I'm not sure I'd want to add something like this to the repo.

**Comment by JulioV** [comment]
Thank you for the pointers! For anyone bumping into this issue and using the material-theme + its `mike` plugin I solved this problem by [extending the theme](https://squidfunk.github.io/mkdocs-material/customization/#additional-css) and adding the following JS and CSS. Note that this relies on having a mike alias called `latest`

```js
window.addEventListener("DOMContentLoaded", function() {
    if(!window.location.pathname.endsWith("/latest/")){
        document.querySelector("div[data-md-component=announce]").innerHTML = "<div id='announce-msg'>You are seeing the docs for a previous version of MY_PROJECT, <a href='latest/'>click here to go to the latest</a></div>"
    }
  });

```

```css
div[data-md-component=announce] {
    background-color: rgba(255,145,0,.1);
}
div[data-md-component=announce]>div#announce-msg{
    color: var(--md-admonition-fg-color);
    font-size: .8rem;
    text-align: center;
    margin: 15px;
}
div[data-md-component=announce]>div#announce-msg>a{
    color: var(--md-typeset-a-color);
    text-decoration: underline;
}
```
