### ISSUE TITLE
Can it support in github action flow

### ISSUE THREAD

**Issue by nianiaJR** [jimporter/mike#28]
I hive config a github workflow like this:
```
name: Publish docs via GitHub Pages
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.7'
          architecture: 'x64'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r ./requirements.txt

      - name: Mike Deploy 2.0
        run: mike deploy 2.0 -p  // I want to trigger mike deploy to gh-pages here
```
But it doesn't work, it out put an error like this:
![image](https://user-images.githubusercontent.com/8124783/99698069-52c06400-2acb-11eb-9b87-4114739c761d.png)

How can I make it? thanks.

**Comment by jimporter** [comment]
In order to generate a commit from a Github Action, you'll need to set a username and email address for git:

```
git config --global user.name Name
git config --global user.email name@domain.com
```

**Comment by nianiaJR** [comment]
Year, I've done this, it works. But another problem exists. When I mike deploy [version] in the workflow. The files pushed to the gh-pages are different from the files I pushed via`mike deploy` local. How to fix that? thanks

**Comment by jimporter** [comment]
What's different, exactly? One possible issue is that you have a different version of some Python package locally than what got installed during your Github Action.

**Comment by nianiaJR** [comment]
Here is the result I mike deploy via github worflow:
![image](https://user-images.githubusercontent.com/8124783/99751458-30573680-2b1d-11eb-8a42-c6444ea10afd.png)
Here is the result I mike deploy via  local:
![image](https://user-images.githubusercontent.com/8124783/99751543-5aa8f400-2b1d-11eb-89c6-4cc4740275fd.png)

**Comment by nianiaJR** [comment]
It seem that lots of files are not upload to the gh-page when mike via workflow. Here is my github action config:
https://github.com/vesoft-inc/nebula-docs/blob/jerry-dev/.github/workflows/deploy.yml

Is there some thing wrong?

**Comment by jimporter** [comment]
Did you add the `-f` here to fix an error from `mike`?

https://github.com/vesoft-inc/nebula-docs/blob/736a5b7970d59a16a9c37b34b3525565af18caf7/.github/workflows/deploy.yml#L32

Generally, the `-f` option should be used with caution since, like `git push -f`, it can overwrite Git history.

My guess is that `mike` is getting confused because the Github Action doesn't know about the `gh-pages` branch, so it thinks there are no previous commits to it. It then creates a completely-new `gh-pages` branch locally, and then with `-p -f`, it gets force-pushed to your main repository, wiping out the previous history of your `gh-pages` branch.

To fix this, I think you could change your checkout action to this:
```yaml
uses: actions/checkout@v2
with:
  fetch-depth: 0 # fetch all commits/branches
```
That should fetch `origin/gh-pages` and then hopefully everything will work. Make sure to remove the `-f` flag from your `mike deploy` call too, since it will tell you if something isn't set up right.
