### ISSUE TITLE
Deploying without `mike deploy`?

### ISSUE THREAD

**Issue by polarathene** [jimporter/mike#44]
Presently I have the build output from `mkdocs build` deployed without using `mkdocs deploy`. I'm not sure if I can keep this workflow if adopting `mike` to add in versioned docs support though?

The present Github Actions workflow for deployment looks like this:

```yml
name: 'Documentation'

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/deploy-docs.yml'
      - 'docs/**'

# Jobs will run shell commands from this subdirectory:
defaults:
  run:
    working-directory: docs

jobs:
  deploy:
    name: 'Deploy Docs'
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: 'Build with mkdocs-material via Docker'
        run: docker run --rm -v ${PWD}:/docs squidfunk/mkdocs-material build --strict

      - name: 'Deploy to Github Pages'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/site
          user_name: 'github-actions[bot]'
          user_email: '41898282+github-actions[bot]@users.noreply.github.com'
```

- The `peaceiris/actions-gh-pages@v3` action is preferred for generic deploys of build output.
- I'm using the docker container for `mkdocs-material` which simplifies maintenance, but it seems to use `mike` I'll need to include additional environment setup to add in python and pip install packages?

My understanding is that the main project docs remain as is, but `mike` will be managing versions with subdirectories of versions/aliases on the `gh-pages` branch, that it's using this branch to add the new build output to the configured location, and pushing that new commit for deployment?

Other `mike` features aside, does that mean as long as I mirror `gh-pages` in `publish_dir` location in my deployment action, and add my build to the correct version subdirectory, I'd have the equivalent of `mike deploy`?
