### ISSUE TITLE
GitHub Actions Refs Error

### ISSUE THREAD

**Issue by sasial-dev** [jimporter/mike#60]
I have a GH Action
```yml
name: Site Deployment

on:
  push:
    branches:
      - docs

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9.x

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set up git author
        run: |
          remote_repo="https://${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git remote rm origin
          git remote add origin "${remote_repo}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy
        run: mike deploy --push --rebase master latest

      - name: List
        run: mike list
```
and I am getting the error
```
error: failed to push branch gh-pages to origin: "To https://github.com/Lundstrong/LundstrongOrders.git
 ! [rejected]        gh-pages -> gh-pages (fetch first)
error: failed to push some refs to 'https://github.com/Lundstrong/LundstrongOrders.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details."

```
How do I fix this, I've looked through the other issues and found no soulution.

**Comment by jimporter** [comment]
The problem you're seeing is because Github makes a shallow checkout when you use `actions/checkout@v2`, which means that when `mike` tries to do its thing on the `gh-pages` branch, it thinks it's a brand-new, empty branch. That works fine until pushing upstream, when it fails for the reason you see.

The easiest solution I know of is to add the following to your checkout action:

```yaml
uses: actions/checkout@v2
with:
  fetch-depth: 0 # fetch all commits/branches
```

There are some more details [in this issue](https://github.com/jimporter/mike/issues/28#issuecomment-730813808) as well.

There might be a better way to do this (which is why I haven't officially-recommended the above in the README), but it should work for you. If not, just let me know. I'll also try and figure out a proper solution to put in the README (or maybe even do something like this automatically?) since it's a subtle issue that tends to trip people up.
