### ISSUE TITLE
mike doesnt support !ENV

### ISSUE THREAD

**Issue by zhilyaev** [jimporter/mike#64]
I have the next `mkdocs.yml`

```
...
extra:
  version:
    provider: mike
    default: latest
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
...
```

## Error

```
error: could not determine a constructor for the tag '!ENV'
  in "mkdocs.yml", line 53, column 15
```

Mkdocs configuration: https://www.mkdocs.org/user-guide/configuration/#environment-variables
