### ISSUE TITLE
Configure all mike yaml options in `plugins:mike:`?

### ISSUE THREAD

**Issue by nejch** [jimporter/mike#75]
Currently `remote_name` and `remote_branch` are configured at the root of `mkdocs.yml`. I think it might be clearer if all options were available in the plugins section, as they're really mike-specific and not mkdocs, even if they're not actually processed by the plugin.

It'd also maybe be easier to bring them closer to the CLI flags and prevent colliding with potential mkdocs-native options or other tooling, as they're scoped to mike. E.g. `remote_name` currently isn't 100% accurate, it can also be a URL, and same with `remote_branch` techinically, without `--push` it's a local branch. https://github.com/jimporter/mike/issues/51 is another candidate maybe. 

So you'd have something like:

```yaml
plugins:
  - mike:
      # these fields are all optional; the defaults are as below...
      branch: gh-pages
      remote: origin
      prefix: ""
      version_selector: true   # set to false to leave out the version selector
      css_dir: css             # the directory to put the version selector's CSS
      javascript_dir: js       # the directory to put the version selector's JS
      canonical_version: null  # the version for <link rel="canonical">; `null`
                               # uses the version specified via `mike deploy`
```

The only thing that feels a bit weird is that since it's not processed by the plugin I guess you'd have to set some dummy defaults there and duplicate them in `load_mkdocs_config()` I suppose :thinking: .
