### ISSUE TITLE
Experiencing `error: [Errno 32] Broken pipe` when using mike in CircleCI

### ISSUE THREAD

**Issue by NunchakusLei** [jimporter/mike#90]
The CircleCI config is,

```
build-docs:
    docker:
      - image: cimg/python:3.10 
    steps:
      - checkout  # Checkout the code as the first step. This is a dedicated CircleCI step.
      ...
      - run:
          name: Install dependencies for docs building
          command: |
            pip install mike
      - run:
          name: Set user
          command: |
            git config --global user.email "autobot@<domain>"
            git config --global user.name "Auto Bot"
      - run:
          name: Build the docs and push to libypc-docs
          command: |
            mike deploy << pipeline.git.tag >> --remote docs-remote --push
            mike set-default << pipeline.git.tag >> --remote docs-remote --push
```

I also try running `mike deploy <a-version>` in the CircleCI and trigger the same error. This error looks like triggered after mkdocs successfully build the documentation since I do see a message like `INFO     -  Documentation built in 7.08 seconds` right before the error. Do you have an idea of where I should check? Let me know if you need more info.
